# KONTi api-server — production Dockerfile for Railway
#
# Why this exists (and not nixpacks.toml):
# Railway's Nixpacks builder ignored every phase override we set and kept
# running `pnpm i --frozen-lockfile` with the auto-detected pnpm-9_x.
# Our lockfile was generated by pnpm 11.1.1 (different overrides hash
# format), so pnpm 9 rejects it with ERR_PNPM_LOCKFILE_CONFIG_MISMATCH.
#
# A Dockerfile takes precedence over Nixpacks in Railway, gives us
# deterministic builds, and lets us pin every version exactly.
#
# Multi-stage:
#   - builder: Node 24 + pnpm 11.1.1, full source, esbuild bundle
#   - runtime: Node 24 alpine, only the bundled dist/

# ─── Stage 1: Build ────────────────────────────────────────────────────────
FROM node:24-alpine AS builder

# Install pnpm at the exact version our lockfile was generated with.
RUN npm install -g pnpm@11.1.1

WORKDIR /app

# Copy the entire workspace. .dockerignore strips local node_modules / dist /
# .git so we don't carry junk into the image.
COPY . .

# Install all workspace dependencies. The lockfile is now pinned to pnpm
# 11.1.1's overrides hash, so --frozen-lockfile succeeds.
RUN pnpm install --frozen-lockfile

# Build the api-server. esbuild bundles every TypeScript source into
# artifacts/api-server/dist/index.mjs plus a handful of pino worker shims.
# Libraries (lib/*) are consumed as source TS via path aliases — no
# separate build step needed for them.
RUN pnpm --filter @workspace/api-server run build


# ─── Stage 2: Runtime ──────────────────────────────────────────────────────
FROM node:24-alpine AS runtime

# Required for `--enable-source-maps` to find the bundled .map files.
ENV NODE_ENV=production

WORKDIR /app

# The esbuild bundle is fully self-contained: no node_modules at runtime.
# Just copy the built dist/ and we're done.
COPY --from=builder /app/artifacts/api-server/dist ./dist

# Railway injects PORT; the api-server reads it via process.env.PORT.
EXPOSE 8080

# --enable-source-maps gives readable stack traces from the bundled output.
# Healthcheck path is /api/health (defined in railway.json).
CMD ["node", "--enable-source-maps", "dist/index.mjs"]
