import { useEffect, useState } from "react";
import { useLang } from "@/hooks/use-lang";
import { useToast } from "@/hooks/use-toast";
import { useListProjects, getGetProjectCalculationsQueryKey } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";
import { Upload, Receipt, FileText, Loader2, Check, ScanLine, Columns3, ChevronDown, ChevronRight } from "lucide-react";
import { getJson, postJson, readFileAsText, ApiError, type LaborRate } from "./estimating-helpers";
import {
  type ImportKind,
  type Mapping,
  parseCsv as parseMappingCsv,
  loadSavedMapping,
  saveMapping,
} from "./column-mapping";
import { MappingDialog } from "./mapping-dialog";
import { MultiItemReceiptScanner } from "./multi-item-receipt-scanner";

const SAMPLE_MATERIALS = `item,item_es,category,unit,base_price
Bamboo Flooring,Piso de Bambú,finishes,sqft,8.50
Recycled Steel Beam I-12,Viga de Acero Reciclado I-12,steel,unit,425
Mineral Wool R-30,Lana Mineral R-30,insulation,roll,72`;

const SAMPLE_LABOR = `trade,trade_es,unit,hourly_rate
General Labor,Mano de Obra General,hour,24
Carpenter,Carpintero,hour,40
Electrician,Electricista,hour,58`;

const SAMPLE_RECEIPTS = `vendor,date,trade,amount,hours
Home Depot,2026-04-10,Carpenter,820,20
Ferretería PR,2026-04-12,Carpenter,880,22
Home Depot,2026-04-15,Carpenter,900,21`;

interface SkippedRow { row: number; reason: string; }
interface UploadResult {
  ok: boolean;
  message: string;
  details?: string;
  skipped?: SkippedRow[];
}

export function ImportsPanel() {
  const { t, lang } = useLang();
  const { toast } = useToast();
  const { data: projects = [] } = useListProjects();
  const queryClient = useQueryClient();
  const [projectId, setProjectId] = useState<string>("");
  const [autoFillProject, setAutoFillProject] = useState<boolean>(true);
  const [matProjectId, setMatProjectId] = useState<string>("");
  const [matCsv, setMatCsv] = useState(SAMPLE_MATERIALS);
  const [labCsv, setLabCsv] = useState(SAMPLE_LABOR);
  const [recCsv, setRecCsv] = useState(SAMPLE_RECEIPTS);
  const tplDefaults = () => ({
    name: t("KONTi Standard v2", "KONTi Estándar v2"),
    columns: t(
      "Category, Item, Qty, Unit, Unit Price, Total",
      "Categoría, Material, Cant., Unidad, Precio Unitario, Total",
    ),
    header: t(
      "KONTi Design | Build Studio\nProject Estimate Report\nConfidential",
      "KONTi Design | Build Studio\nReporte de Estimado de Proyecto\nConfidencial",
    ),
    footer: t(
      "Generated by KONTi Dashboard · konti.com",
      "Generado por KONTi Dashboard · konti.com",
    ),
  });
  const [tplName, setTplName] = useState(() => tplDefaults().name);
  const [tplColumns, setTplColumns] = useState(() => tplDefaults().columns);
  const [tplHeader, setTplHeader] = useState(() => tplDefaults().header);
  const [tplFooter, setTplFooter] = useState(() => tplDefaults().footer);
  const [tplDirty, setTplDirty] = useState({ name: false, columns: false, header: false, footer: false });
  useEffect(() => {
    const d = tplDefaults();
    setTplName((prev) => (tplDirty.name ? prev : d.name));
    setTplColumns((prev) => (tplDirty.columns ? prev : d.columns));
    setTplHeader((prev) => (tplDirty.header ? prev : d.header));
    setTplFooter((prev) => (tplDirty.footer ? prev : d.footer));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [lang]);
  const [matResult, setMatResult] = useState<UploadResult | null>(null);
  const [labResult, setLabResult] = useState<UploadResult | null>(null);
  const [recResult, setRecResult] = useState<UploadResult | null>(null);
  const [tplResult, setTplResult] = useState<UploadResult | null>(null);
  const [busy, setBusy] = useState<string | null>(null);
  const [labRates, setLabRates] = useState<LaborRate[]>([]);

  // OCR file upload state
  const [ocrFile, setOcrFile] = useState<File | null>(null);
  const [ocrTrade, setOcrTrade] = useState<string>("");
  const [ocrHours, setOcrHours] = useState<string>("");
  const [ocrAmount, setOcrAmount] = useState<string>("");
  const [ocrVendor, setOcrVendor] = useState<string>("");
  const [ocrDate, setOcrDate] = useState<string>("");
  const [ocrResult, setOcrResult] = useState<UploadResult | null>(null);
  const [ocrExtracted, setOcrExtracted] = useState<{ vendor?: string; date?: string; amount?: number; hours?: number } | null>(null);

  useEffect(() => {
    if (!projectId && projects[0]) setProjectId(projects[0].id);
    if (!matProjectId && projects[0]) setMatProjectId(projects[0].id);
  }, [projects, projectId, matProjectId]);

  useEffect(() => {
    getJson<{ rates: LaborRate[] }>("/api/estimating/labor-rates").then((d) => setLabRates(d.rates)).catch(() => undefined);
  }, [labResult, recResult]);

  const handleFileSelect = async (file: File | undefined, setter: (s: string) => void) => {
    if (!file) return;
    try { setter(await readFileAsText(file)); }
    catch { toast({ title: t("Could not read file", "No se pudo leer el archivo"), variant: "destructive" }); }
  };

  const skippedSummary = (n: number) => (n ? t(`${n} skipped`, `${n} omitidos`) : undefined);

  const failureFromError = (e: unknown): UploadResult => {
    if (e instanceof ApiError) {
      const skippedDetails = Array.isArray(e.payload["skippedDetails"])
        ? (e.payload["skippedDetails"] as SkippedRow[])
        : undefined;
      const messageEs = typeof e.payload["messageEs"] === "string" ? (e.payload["messageEs"] as string) : undefined;
      return {
        ok: false,
        message: t(e.message, messageEs ?? e.message),
        skipped: skippedDetails,
        details: skippedDetails && skippedDetails.length > 0 ? skippedSummary(skippedDetails.length) : undefined,
      };
    }
    return { ok: false, message: e instanceof Error ? e.message : "error" };
  };

  const importMaterials = async (mapping: Mapping | null) => {
    setBusy("mat");
    try {
      const targetProject = autoFillProject && matProjectId ? matProjectId : undefined;
      const payload: Record<string, unknown> = { csv: matCsv };
      if (targetProject) payload["projectId"] = targetProject;
      if (mapping) payload["mapping"] = mapping;
      const r = await postJson<{
        imported: number;
        skipped: number;
        skippedDetails?: SkippedRow[];
        addedToProjectCalculator?: number;
      }>("/api/estimating/materials/import", payload);
      const addedNote = (r.addedToProjectCalculator ?? 0) > 0
        ? t(`${r.addedToProjectCalculator} added to project calculator`, `${r.addedToProjectCalculator} agregadas a la calculadora`)
        : undefined;
      setMatResult({
        ok: true,
        message: t(`Imported ${r.imported} material(s)`, `Importados ${r.imported} material(es)`),
        details: [skippedSummary(r.skipped), addedNote].filter(Boolean).join(" · ") || undefined,
        skipped: r.skippedDetails,
      });
      if (mapping && matProjectId) saveMapping(matProjectId, "materials", mapping);
      if (targetProject && (r.addedToProjectCalculator ?? 0) > 0) {
        queryClient.invalidateQueries({ queryKey: getGetProjectCalculationsQueryKey(targetProject) });
        toast({
          title: t("Calculator updated", "Calculadora actualizada"),
          description: t(
            `${r.addedToProjectCalculator} new line(s) added to the project calculator`,
            `${r.addedToProjectCalculator} nueva(s) línea(s) en la calculadora del proyecto`,
          ),
        });
      }
    } catch (e) { setMatResult(failureFromError(e)); }
    finally { setBusy(null); }
  };
  const importLabor = async (mapping: Mapping | null) => {
    setBusy("lab");
    try {
      const payload: Record<string, unknown> = { csv: labCsv };
      if (mapping) payload["mapping"] = mapping;
      const r = await postJson<{
        imported: number;
        skipped: number;
        skippedDetails?: SkippedRow[];
      }>("/api/estimating/labor-rates/import", payload);
      setLabResult({
        ok: true,
        message: t(`Imported ${r.imported} labor rate(s)`, `Importadas ${r.imported} tarifa(s)`),
        details: skippedSummary(r.skipped),
        skipped: r.skippedDetails,
      });
      if (mapping && projectId) saveMapping(projectId, "labor", mapping);
    } catch (e) { setLabResult(failureFromError(e)); }
    finally { setBusy(null); }
  };
  const uploadReceipts = async (mapping: Mapping | null) => {
    if (!projectId) return;
    setBusy("rec");
    try {
      const payload: Record<string, unknown> = { csv: recCsv };
      if (mapping) payload["mapping"] = mapping;
      const r = await postJson<{
        receipts: unknown[];
        updatedTrades: string[];
        imported?: number;
        skipped?: number;
        skippedDetails?: SkippedRow[];
      }>(`/api/projects/${projectId}/receipts`, payload);
      const tradesNote = t(`Refreshed labor for: ${r.updatedTrades.join(", ") || "—"}`, `Tarifas actualizadas: ${r.updatedTrades.join(", ") || "—"}`);
      setRecResult({
        ok: true,
        message: t(`Saved ${r.receipts.length} receipt(s)`, `${r.receipts.length} recibo(s) guardado(s)`),
        details: [tradesNote, skippedSummary(r.skipped ?? 0)].filter(Boolean).join(" · "),
        skipped: r.skippedDetails,
      });
      if (mapping && projectId) saveMapping(projectId, "receipts", mapping);
    } catch (e) { setRecResult(failureFromError(e)); }
    finally { setBusy(null); }
  };
  const uploadOcrReceipt = async () => {
    if (!projectId || !ocrFile || !ocrTrade) return;
    setBusy("ocr");
    setOcrResult(null);
    setOcrExtracted(null);
    try {
      const fileBase64 = await fileToBase64(ocrFile);
      const payload: Record<string, unknown> = {
        fileBase64,
        filename: ocrFile.name,
        trade: ocrTrade,
      };
      if (ocrVendor.trim()) payload["vendor"] = ocrVendor.trim();
      if (ocrDate.trim()) payload["date"] = ocrDate.trim();
      if (ocrAmount.trim()) payload["amount"] = Number(ocrAmount);
      if (ocrHours.trim()) payload["hours"] = Number(ocrHours);

      type UploadResp = {
        receipts: Array<{ vendor: string; amount: number; hours: number }>;
        updatedTrades: string[];
        ocrExtracted?: { vendor?: string; date?: string; amount?: number; hours?: number };
      };
      const r = await postJson<UploadResp>(`/api/projects/${projectId}/receipts/upload-file`, payload);
      setOcrExtracted(r.ocrExtracted ?? null);
      setOcrResult({
        ok: true,
        message: t(
          `Receipt saved (${r.receipts.length} on file). Trades refreshed: ${r.updatedTrades.join(", ") || "—"}.`,
          `Recibo guardado (${r.receipts.length} en total). Tarifas actualizadas: ${r.updatedTrades.join(", ") || "—"}.`,
        ),
      });
      // Reset file/inputs but keep the trade selection for the next upload.
      setOcrFile(null);
      setOcrHours("");
      setOcrAmount("");
      setOcrVendor("");
      setOcrDate("");
      toast({
        title: t("Receipt processed", "Recibo procesado"),
        description: t("Labor baseline updated from the new receipt.", "La línea base de mano de obra fue actualizada."),
      });
    } catch (e) {
      const msg = e instanceof Error ? e.message : "error";
      setOcrResult({ ok: false, message: msg });
    } finally {
      setBusy(null);
    }
  };

  const uploadTemplate = async () => {
    if (!projectId) return;
    setBusy("tpl");
    try {
      await postJson(`/api/projects/${projectId}/report-template`, {
        name: tplName,
        columns: tplColumns.split(",").map((s) => s.trim()).filter(Boolean),
        headerLines: tplHeader.split("\n").map((s) => s.trim()).filter(Boolean),
        footer: tplFooter.trim(),
      });
      setTplResult({ ok: true, message: t("Report template saved. Future PDF exports will use this layout.", "Plantilla guardada. Las próximas exportaciones a PDF usarán este formato.") });
    } catch (e) { setTplResult({ ok: false, message: e instanceof Error ? e.message : "error" }); }
    finally { setBusy(null); }
  };

  return (
    <div className="space-y-5" data-testid="imports-panel">
      {/* P5.2 / P5.4 — Multi-item receipt scanner. Replaces the single-row
          OCR flow for receipts with multiple materials (e.g. a Home Depot
          trip). Includes the chargeable toggle per line. */}
      <MultiItemReceiptScanner />

      {/* What "Imports" means — banner so the team isn't guessing whether this
          is a separate cost category or just a bulk-load tool. */}
      <div
        className="bg-konti-olive/5 border border-konti-olive/30 rounded-lg p-3 text-xs text-foreground flex items-start gap-2"
        data-testid="imports-explainer"
      >
        <span
          aria-hidden
          className="inline-flex items-center justify-center w-4 h-4 rounded-full bg-konti-olive/20 text-konti-olive text-[10px] font-bold shrink-0 mt-0.5"
        >
          ?
        </span>
        <span>
          <span className="font-semibold">{t("What is this tab?", "¿Qué es esta pestaña?")}</span>{" "}
          {t(
            "Bulk-load your existing materials catalog, labor rates, paper receipts, and report templates. Imported items are not a separate cost line — they merge into the standard Materials, Labor, and Receipts buckets used by the calculator.",
            "Carga masiva de tu catálogo de materiales, tarifas de mano de obra, recibos en papel y plantillas de reporte. Los elementos importados no son una categoría separada — se integran a Materiales, Mano de Obra y Recibos que usa la calculadora.",
          )}
        </span>
      </div>

      {/* Materials import */}
      <Section
        icon={<Upload className="w-4 h-4 text-konti-olive" />}
        title={t("Import Materials & Categories", "Importar Materiales y Categorías")}
        description={t("Pick a spreadsheet (CSV or Excel). KONTi auto-matches your column headers to item, category, unit, and base price — review or override before confirming.", "Elige una hoja (CSV o Excel). KONTi auto-detecta tus columnas (artículo, categoría, unidad y precio base) — revisa o ajusta antes de confirmar.")}
        onFile={(f) => handleFileSelect(f, setMatCsv)}
        textValue={matCsv} setText={setMatCsv}
        onImport={importMaterials} busy={busy === "mat"} result={matResult} testid="import-materials"
        kind="materials" projectId={matProjectId}
        extra={
          <div className="mt-3 border border-dashed border-border rounded-md p-3 bg-muted/20" data-testid="materials-target-project">
            <label className="flex items-center gap-2 text-xs font-semibold cursor-pointer">
              <input
                type="checkbox"
                checked={autoFillProject}
                onChange={(e) => setAutoFillProject(e.target.checked)}
                data-testid="materials-autofill-toggle"
                className="accent-konti-olive"
              />
              {t("Auto-populate calculator after import", "Auto-completar la calculadora tras importar")}
            </label>
            <p className="text-[11px] text-muted-foreground mt-1 mb-2">
              {t(
                "Each imported material is appended as a new calculator line (qty 1) for the selected project so the team can adjust quantities and overrides.",
                "Cada material importado se agrega como una línea nueva (cant. 1) en la calculadora del proyecto seleccionado para que el equipo ajuste cantidades y sobrescrituras.",
              )}
            </p>
            <label className="text-[11px] font-medium space-y-1 block">
              {t("Target project", "Proyecto destino")}
              <select
                value={matProjectId}
                onChange={(e) => setMatProjectId(e.target.value)}
                disabled={!autoFillProject}
                data-testid="materials-target-project-select"
                className="w-full mt-1 px-2.5 py-1.5 rounded border border-input bg-background text-xs disabled:opacity-50"
              >
                {projects.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}
              </select>
            </label>
          </div>
        }
      />

      {/* Labor rates */}
      <Section
        icon={<FileText className="w-4 h-4 text-konti-olive" />}
        title={t("Import Labor Rates", "Importar Tarifas de Mano de Obra")}
        description={t("Pick a spreadsheet of trades and hourly rates — KONTi auto-detects the columns. Existing trades update in place; new trades are appended.", "Elige una hoja de oficios y tarifas — KONTi detecta las columnas. Los oficios existentes se actualizan y los nuevos se agregan.")}
        onFile={(f) => handleFileSelect(f, setLabCsv)}
        textValue={labCsv} setText={setLabCsv}
        onImport={importLabor} busy={busy === "lab"} result={labResult} testid="import-labor"
        kind="labor" projectId={projectId}
      />
      {labRates.length > 0 && (
        <div className="bg-card rounded-lg border border-card-border p-4">
          <div className="flex items-center gap-1.5 mb-2">
            <p className="text-xs font-semibold text-foreground">{t("Current labor baseline (effective rate)", "Línea base actual (tarifa efectiva)")}</p>
            <button
              type="button"
              aria-label={t("Effective rate explanation", "Explicación de tarifa efectiva")}
              title={t(
                "The effective rate is the hourly cost actually used in estimates. When tagged 'receipts', it's recomputed from the 3 most recent uploaded receipts (total amount ÷ total hours). When tagged 'import', it comes from the latest CSV import. 'default' means no overrides yet.",
                "La tarifa efectiva es el costo por hora usado en los estimados. Cuando aparece 'receipts', se recalcula con los 3 recibos más recientes (monto total ÷ horas totales). 'import' indica que viene del último CSV. 'default' significa que aún no hay sobrescrituras.",
              )}
              className="inline-flex items-center justify-center w-4 h-4 rounded-full border border-border text-[10px] font-semibold text-muted-foreground cursor-help leading-none focus:outline-none focus-visible:ring-2 focus-visible:ring-konti-olive focus-visible:ring-offset-1 hover:bg-muted hover:text-foreground transition-colors"
              data-testid="effective-rate-tooltip"
            >
              ?
            </button>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-2 text-xs">
            {labRates.map((r) => (
              <div key={r.trade} className="flex items-center justify-between bg-muted/40 px-2.5 py-1.5 rounded">
                <span>{lang === "es" ? r.tradeEs : r.trade}</span>
                <span className="font-bold">${r.hourlyRate.toFixed(2)}/{r.unit}</span>
                <span className={`ml-2 px-1.5 py-0.5 rounded text-[10px] font-semibold ${r.source === "receipts" ? "bg-konti-olive/15 text-konti-olive" : r.source === "import" ? "bg-blue-100 text-blue-700" : "bg-muted text-muted-foreground"}`}>{r.source}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Receipts — OCR upload (PDF or image) */}
      <div className="bg-card rounded-xl border border-card-border p-5 shadow-sm" data-testid="receipts-ocr-panel">
        <div className="flex items-center justify-between flex-wrap gap-3 mb-2">
          <div className="flex items-center gap-2">
            <ScanLine className="w-4 h-4 text-konti-olive" />
            <h3 className="font-bold text-sm">{t("Scan Paper Receipt (PDF or Photo)", "Escanear Recibo (PDF o Foto)")}</h3>
          </div>
          <select value={projectId} onChange={(e) => setProjectId(e.target.value)} className="px-2.5 py-1.5 rounded border border-input bg-background text-xs" data-testid="receipts-project">
            {projects.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}
          </select>
        </div>
        <p className="text-xs text-muted-foreground mb-3">
          {t(
            "Upload a PDF or photo of a paper receipt. The server runs OCR (PDF.co) and extracts vendor, date, and total. Pick the trade and (if not auto-detected) enter hours. The labor baseline is recomputed from the 3 most recent receipts.",
            "Sube un PDF o foto del recibo. El servidor ejecuta OCR (PDF.co) y extrae proveedor, fecha y total. Selecciona el oficio y (si no se detecta) ingresa las horas. La línea base de mano de obra se recalcula con los 3 recibos más recientes."
          )}
        </p>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
          <label className="space-y-1 block md:col-span-2">
            <span className="font-medium">{t("Receipt file (PDF, JPG, PNG)", "Archivo de recibo (PDF, JPG, PNG)")}</span>
            <input
              type="file"
              accept="application/pdf,image/png,image/jpeg,image/jpg,image/webp,image/gif"
              onChange={(e) => setOcrFile(e.target.files?.[0] ?? null)}
              data-testid="receipt-ocr-file"
              className="block w-full text-xs"
            />
            {ocrFile && (
              <span className="text-[11px] text-muted-foreground">
                {ocrFile.name} · {(ocrFile.size / 1024).toFixed(0)} KB
              </span>
            )}
          </label>
          <label className="space-y-1 block">
            <span className="font-medium">{t("Trade (required)", "Oficio (requerido)")}</span>
            <select
              value={ocrTrade}
              onChange={(e) => setOcrTrade(e.target.value)}
              data-testid="receipt-ocr-trade"
              className="w-full mt-1 px-2.5 py-1.5 rounded border border-input bg-background"
            >
              <option value="">{t("— select trade —", "— selecciona oficio —")}</option>
              {labRates.map((r) => (
                <option key={r.trade} value={r.trade}>{lang === "es" ? r.tradeEs : r.trade}</option>
              ))}
            </select>
          </label>
          <label className="space-y-1 block">
            <span className="font-medium">{t("Hours (optional override)", "Horas (sobrescribir opcional)")}</span>
            <input
              type="number"
              min="0"
              step="0.25"
              value={ocrHours}
              onChange={(e) => setOcrHours(e.target.value)}
              placeholder={t("e.g. 8", "ej. 8")}
              data-testid="receipt-ocr-hours"
              className="w-full mt-1 px-2.5 py-1.5 rounded border border-input bg-background"
            />
          </label>
          <label className="space-y-1 block">
            <span className="font-medium">{t("Vendor (optional override)", "Proveedor (opcional)")}</span>
            <input
              value={ocrVendor}
              onChange={(e) => setOcrVendor(e.target.value)}
              placeholder={t("Auto-detected if blank", "Auto-detectado si está vacío")}
              data-testid="receipt-ocr-vendor"
              className="w-full mt-1 px-2.5 py-1.5 rounded border border-input bg-background"
            />
          </label>
          <label className="space-y-1 block">
            <span className="font-medium">{t("Date (optional override)", "Fecha (opcional)")}</span>
            <input
              type="date"
              value={ocrDate}
              onChange={(e) => setOcrDate(e.target.value)}
              data-testid="receipt-ocr-date"
              className="w-full mt-1 px-2.5 py-1.5 rounded border border-input bg-background"
            />
          </label>
          <label className="space-y-1 block md:col-span-2">
            <span className="font-medium">{t("Amount (optional override)", "Monto (opcional)")}</span>
            <input
              type="number"
              min="0"
              step="0.01"
              value={ocrAmount}
              onChange={(e) => setOcrAmount(e.target.value)}
              placeholder={t("Auto-detected if blank", "Auto-detectado si está vacío")}
              data-testid="receipt-ocr-amount"
              className="w-full mt-1 px-2.5 py-1.5 rounded border border-input bg-background"
            />
          </label>
        </div>
        <div className="flex items-center gap-3 mt-3 flex-wrap">
          <button
            onClick={uploadOcrReceipt}
            disabled={busy === "ocr" || !projectId || !ocrFile || !ocrTrade}
            data-testid="btn-upload-ocr-receipt"
            className="inline-flex items-center gap-2 px-3 py-1.5 bg-konti-olive hover:bg-konti-olive/90 text-white text-xs font-semibold rounded-md disabled:opacity-50"
          >
            {busy === "ocr" ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <ScanLine className="w-3.5 h-3.5" />}
            {t("Scan & Save Receipt", "Escanear y Guardar Recibo")}
          </button>
          {ocrResult && (
            <span className={`text-xs ${ocrResult.ok ? "text-konti-olive" : "text-destructive"}`} data-testid="receipt-ocr-result">
              {ocrResult.message}
            </span>
          )}
        </div>
        {ocrExtracted && (ocrExtracted.vendor || ocrExtracted.date || ocrExtracted.amount || ocrExtracted.hours) && (
          <div className="mt-3 border border-dashed border-border rounded-md p-3 bg-muted/20 text-xs" data-testid="receipt-ocr-extracted">
            <p className="font-semibold mb-1">{t("Extracted from OCR", "Extraído por OCR")}</p>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
              <Field label={t("Vendor", "Proveedor")} value={ocrExtracted.vendor ?? "—"} />
              <Field label={t("Date", "Fecha")} value={ocrExtracted.date ?? "—"} />
              <Field label={t("Amount", "Monto")} value={ocrExtracted.amount !== undefined ? `$${ocrExtracted.amount.toFixed(2)}` : "—"} />
              <Field label={t("Hours", "Horas")} value={ocrExtracted.hours !== undefined ? String(ocrExtracted.hours) : "—"} />
            </div>
          </div>
        )}
      </div>

      {/* Receipts — CSV fallback (kept for batch entry / spreadsheets) */}
      <Section
        icon={<Receipt className="w-4 h-4 text-konti-olive" />}
        title={t("Bulk Receipts (CSV)", "Recibos en Lote (CSV)")}
        description={t(
          "Pick a spreadsheet of vendor receipts. KONTi auto-matches vendor, date, trade, amount, and hours columns. The 3 most recent are kept and the labor baseline is recomputed.",
          "Elige una hoja de recibos. KONTi detecta vendor, date, trade, amount y hours. Se conservan los 3 más recientes y se recalcula la línea base."
        )}
        onFile={(f) => handleFileSelect(f, setRecCsv)}
        textValue={recCsv} setText={setRecCsv}
        onImport={uploadReceipts} busy={busy === "rec"} result={recResult} testid="import-receipts"
        kind="receipts" projectId={projectId}
        extra={
          <div className="mt-3 border border-dashed border-border rounded-md p-3 bg-muted/20">
            <label className="text-[11px] font-medium space-y-1 block">
              {t("Project", "Proyecto")}
              <select
                value={projectId}
                onChange={(e) => setProjectId(e.target.value)}
                data-testid="receipts-csv-project"
                className="w-full mt-1 px-2.5 py-1.5 rounded border border-input bg-background text-xs"
              >
                {projects.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}
              </select>
            </label>
          </div>
        }
      />

      {/* Report template */}
      <div className="bg-card rounded-xl border border-card-border p-5 shadow-sm">
        <div className="flex items-center gap-2 mb-2">
          <FileText className="w-4 h-4 text-konti-olive" />
          <h3 className="font-bold text-sm">{t("Report Template", "Plantilla de Reporte")}</h3>
        </div>
        <p className="text-xs text-muted-foreground mb-3">
          {t(
            "Define the columns, header, and footer the PDF export should reuse. Persists per project for the demo session.",
            "Define las columnas, encabezado y pie que el PDF reutilizará. Se guarda por proyecto durante la sesión demo."
          )}
        </p>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-2 text-xs">
          <label className="space-y-1 block">
            {t("Template name", "Nombre de la plantilla")}
            <input
              value={tplName}
              onChange={(e) => { setTplName(e.target.value); setTplDirty((d) => ({ ...d, name: true })); }}
              data-testid="tpl-name"
              className="w-full mt-1 px-2.5 py-1.5 rounded border border-input bg-background"
            />
          </label>
          <label className="space-y-1 block">
            {t("Project", "Proyecto")}
            <select value={projectId} onChange={(e) => setProjectId(e.target.value)} className="w-full mt-1 px-2.5 py-1.5 rounded border border-input bg-background">
              {projects.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}
            </select>
          </label>
          <label className="space-y-1 block md:col-span-2">
            {t("Columns (comma-separated)", "Columnas (separadas por coma)")}
            <input
              value={tplColumns}
              onChange={(e) => { setTplColumns(e.target.value); setTplDirty((d) => ({ ...d, columns: true })); }}
              data-testid="tpl-columns"
              className="w-full mt-1 px-2.5 py-1.5 rounded border border-input bg-background"
            />
          </label>
          <label className="space-y-1 block md:col-span-2">
            {t("Header lines (one per line)", "Líneas de encabezado (una por línea)")}
            <textarea
              value={tplHeader}
              onChange={(e) => { setTplHeader(e.target.value); setTplDirty((d) => ({ ...d, header: true })); }}
              data-testid="tpl-header"
              rows={3}
              className="w-full mt-1 px-2.5 py-1.5 rounded border border-input bg-background font-mono"
            />
          </label>
          <label className="space-y-1 block md:col-span-2">
            {t("Footer", "Pie")}
            <input
              value={tplFooter}
              onChange={(e) => { setTplFooter(e.target.value); setTplDirty((d) => ({ ...d, footer: true })); }}
              data-testid="tpl-footer"
              className="w-full mt-1 px-2.5 py-1.5 rounded border border-input bg-background"
            />
          </label>
        </div>
        <div className="flex items-center gap-3 mt-3">
          <button onClick={uploadTemplate} disabled={busy === "tpl" || !projectId} data-testid="btn-save-template" className="inline-flex items-center gap-2 px-3 py-1.5 bg-konti-olive hover:bg-konti-olive/90 text-white text-xs font-semibold rounded-md disabled:opacity-50">
            {busy === "tpl" ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Upload className="w-3.5 h-3.5" />}
            {t("Save Template", "Guardar Plantilla")}
          </button>
          {tplResult && <span className={`text-xs ${tplResult.ok ? "text-konti-olive" : "text-destructive"}`}>{tplResult.message}</span>}
        </div>
      </div>
    </div>
  );
}

function fileToBase64(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const r = new FileReader();
    r.onload = () => {
      const result = String(r.result ?? "");
      // strip "data:<mime>;base64," prefix to send a raw base64 payload
      const idx = result.indexOf(",");
      resolve(idx >= 0 ? result.slice(idx + 1) : result);
    };
    r.onerror = () => reject(new Error("file_read_error"));
    r.readAsDataURL(file);
  });
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex flex-col">
      <span className="text-[10px] uppercase tracking-wide text-muted-foreground">{label}</span>
      <span className="font-mono">{value}</span>
    </div>
  );
}

// Translate a few well-known server reason codes into bilingual user copy.
// Anything unknown falls back to the raw server string in both languages.
function translateSkipReason(raw: string, lang: "en" | "es"): string {
  const r = raw.toLowerCase();
  if (r.includes("missing item") || r.includes("item/category/unit/price")) {
    return lang === "es"
      ? "faltan artículo, categoría, unidad o precio"
      : "missing item, category, unit, or price";
  }
  if (r.includes("missing trade") && r.includes("rate")) {
    return lang === "es" ? "falta el oficio o la tarifa" : "missing trade or rate";
  }
  if (r.includes("vendor") || r.includes("amount/hours")) {
    return lang === "es"
      ? "faltan proveedor/oficio o monto/horas no son positivos"
      : "missing vendor/trade or non-positive amount/hours";
  }
  return raw;
}

function SkippedDetails({ rows, testid }: { rows: SkippedRow[]; testid: string }) {
  const { t, lang } = useLang();
  const [open, setOpen] = useState(false);
  if (!rows || rows.length === 0) return null;
  return (
    <div className="mt-2 border border-amber-300/50 bg-amber-50 rounded-md text-xs" data-testid={testid}>
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        data-testid={`${testid}-toggle`}
        className="w-full flex items-center justify-between gap-2 px-3 py-1.5 font-semibold text-amber-900 hover:bg-amber-100/60 rounded-md"
      >
        <span className="flex items-center gap-1.5">
          {open ? <ChevronDown className="w-3.5 h-3.5" /> : <ChevronRight className="w-3.5 h-3.5" />}
          {t(`${rows.length} row(s) skipped — see why`, `${rows.length} fila(s) omitida(s) — ver por qué`)}
        </span>
      </button>
      {open && (
        <ul className="px-3 pb-2 space-y-1 list-none" data-testid={`${testid}-list`}>
          {rows.map((r, i) => (
            <li key={i} className="flex items-start gap-2 text-amber-900">
              <span className="font-mono shrink-0">{t(`Row ${r.row}`, `Fila ${r.row}`)}:</span>
              <span>{translateSkipReason(r.reason, lang)}</span>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

function Section({
  icon, title, description, onFile, textValue, setText, onImport, busy, result, testid, extra,
  kind, projectId,
}: {
  icon: React.ReactNode;
  title: string;
  description: string;
  onFile: (file?: File) => void;
  textValue: string;
  setText: (s: string) => void;
  onImport: (mapping: Mapping | null) => Promise<void> | void;
  busy: boolean;
  result: UploadResult | null;
  testid: string;
  extra?: React.ReactNode;
  kind: ImportKind;
  projectId: string;
}) {
  const { t } = useLang();
  const [open, setOpen] = useState(false);
  const [savedMapping, setSavedMapping] = useState<Mapping | null>(null);
  const [loadingSaved, setLoadingSaved] = useState(false);

  const parsed = parseMappingCsv(textValue);
  const canMap = parsed.headers.length > 0 && parsed.rows.length > 0;

  const openDialog = async () => {
    if (!canMap) return;
    if (projectId) {
      setLoadingSaved(true);
      const m = await loadSavedMapping(projectId, kind);
      setSavedMapping(m);
      setLoadingSaved(false);
    } else {
      setSavedMapping(null);
    }
    setOpen(true);
  };
  const handleConfirm = async (mapping: Mapping) => {
    await onImport(mapping);
    setOpen(false);
  };

  return (
    <div className="bg-card rounded-xl border border-card-border p-5 shadow-sm" data-testid={testid}>
      <div className="flex items-center gap-2 mb-2">{icon}<h3 className="font-bold text-sm">{title}</h3></div>
      <p className="text-xs text-muted-foreground mb-3">{description}</p>
      <div className="flex items-center gap-2 mb-2">
        <input
          type="file"
          accept=".csv,.xlsx,.xls,text/csv,text/plain,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel"
          onChange={(e) => onFile(e.target.files?.[0])}
          className="text-xs"
          data-testid={`${testid}-file`}
        />
        <span className="text-[10px] text-muted-foreground">{t("or paste below", "o pega abajo")}</span>
      </div>
      <textarea
        value={textValue}
        onChange={(e) => setText(e.target.value)}
        rows={5}
        className="w-full font-mono text-xs px-3 py-2 rounded border border-input bg-background"
        data-testid={`${testid}-textarea`}
      />

      <div className="flex items-center gap-3 mt-3 flex-wrap">
        <button
          onClick={openDialog}
          disabled={!canMap || busy || loadingSaved}
          data-testid={`${testid}-map-btn`}
          className="inline-flex items-center gap-2 px-3 py-1.5 bg-konti-olive hover:bg-konti-olive/90 text-white text-xs font-semibold rounded-md disabled:opacity-50"
        >
          {busy || loadingSaved ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Columns3 className="w-3.5 h-3.5" />}
          {t("Map Columns & Import", "Mapear Columnas e Importar")}
        </button>
        {result && (
          <span
            className={`text-xs ${result.ok ? "text-konti-olive" : "text-destructive"}`}
            data-testid={`${testid}-result`}
          >
            {result.message}{result.details ? ` · ${result.details}` : ""}
          </span>
        )}
      </div>
      {result?.skipped && result.skipped.length > 0 && (
        <SkippedDetails rows={result.skipped} testid={`${testid}-skipped`} />
      )}
      {extra}

      <MappingDialog
        open={open}
        onClose={() => setOpen(false)}
        onConfirm={handleConfirm}
        kind={kind}
        parsed={parsed}
        initialMapping={savedMapping}
        busy={busy}
        testid={`${testid}-mapping-dialog`}
      />
    </div>
  );
}

export default ImportsPanel;
